title = "TechSalerno"
baseURL = "https://techsalerno.github.io"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The hub for tech in Salerno"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/TechSalerno/"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/salerno_day.jpg"
  recent_posts_number = 2
